# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='luid',
            field=models.CharField(max_length=32, unique=True, null=True, help_text='labplore用户id'),
        ),
    ]
